Updates to gene/affecting_entity_phenotype service to work with relat…
phenoscape/phenoscape-kb-services pull request #363
Opened 2020-12-15 04:19 UTC by Shalsh23

…ion graphs

2020-12-16 16:33 UTC, balhoff requested changes

2020-12-16 16:33 UTC, balhoff commented on src/main/scala/org/phenoscape/kb/queries/GeneAffectingPhenotype.scala
> +          if (parts) sparql"?phenotype $phenotype_of/$part_of $e . "
Probably should be `$phenotype_of|($phenotype_of/$part_of)`

2020-12-17 19:50 UTC, Shalsh23 commented
Test 1:
iri: `http://purl.obolibrary.org/obo/UBERON_0008897`
quality: _
parts: `false`
historical_homologs: `false`
serial_homologs: `false`
limit: `20`
offset: `0`
total: `true`

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 504
}
```

New KB:
```
curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":0}
```

2020-12-17 21:00 UTC, Shalsh23 commented
Test 2:
iri: `http://purl.obolibrary.org/obo/UBERON_0000970`
quality: _
parts: `false`
historical_homologs: `false`
serial_homologs: `false`
limit: `20`
offset: `0`
total: `true`

```
curl -X GET "https://kb.phenoscape.org/api/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000970&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 4813
}
```

New KB:
```
curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000970&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":0}
```

2021-01-26 01:58 UTC, balhoff commented
I pushed a commit that is at least a partial fix. Needs more testing.

2021-01-29 19:59 UTC, Shalsh23 commented
> Test 1:
> iri: `http://purl.obolibrary.org/obo/UBERON_0008897`
> quality: _
> parts: `false`
> historical_homologs: `false`
> serial_homologs: `false`
> limit: `20`
> offset: `0`
> total: `true`
> 
> Old KB:
> 
> ```
> curl -X GET "https://kb.phenoscape.org/api/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
> ```
> 
> ```
> {
>   "total": 504
> }
> ```
> 
> New KB:
> 
> ```
> curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
> ```
> 
> ```
> {"total":0}
> ```

Test 1 results after edits:

New KB:
```
curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":315}
```

2021-01-29 20:00 UTC, Shalsh23 commented
> Test 2:
> iri: `http://purl.obolibrary.org/obo/UBERON_0000970`
> quality: _
> parts: `false`
> historical_homologs: `false`
> serial_homologs: `false`
> limit: `20`
> offset: `0`
> total: `true`
> 
> ```
> curl -X GET "https://kb.phenoscape.org/api/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000970&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
> ```
> 
> ```
> {
>   "total": 4813
> }
> ```
> 
> New KB:
> 
> ```
> curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000970&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
> ```
> 
> ```
> {"total":0}
> ```

Test 2 results after edits:

New KB:
```
curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000970&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":3363}
```

2021-01-29 21:16 UTC, Shalsh23 commented
Test 3:

iri: `http://purl.obolibrary.org/obo/UBERON_0001793`
quality: `http://purl.obolibrary.org/obo/PATO_0001995`
parts: `false`
historical_homologs: `false`
serial_homologs: `false`
limit: `20`
offset: `0`
total: `true`

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001793&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001995&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 6
}
```

New KB:
```
curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001793&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001995&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":0}
```

2021-02-08 22:08 UTC, Shalsh23 commented
> http://purl.obolibrary.org/obo/PATO_0001995

Need to run the above tests with `http://www.ontobee.org/ontology/PATO?iri=http://purl.obolibrary.org/obo/PATO_0000001` and see if we get results.

2021-02-09 18:04 UTC, Shalsh23 commented
> Test 3:
> 
> iri: `http://purl.obolibrary.org/obo/UBERON_0001793`
> quality: `http://purl.obolibrary.org/obo/PATO_0001995`
> parts: `false`
> historical_homologs: `false`
> serial_homologs: `false`
> limit: `20`
> offset: `0`
> total: `true`
> 
> Old KB:
> 
> ```
> curl -X GET "https://kb.phenoscape.org/api/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001793&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001995&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
> ```
> 
> ```
> {
>   "total": 6
> }
> ```
> 
> New KB:
> 
> ```
> curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001793&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001995&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
> ```
> 
> ```
> {"total":0}
> ```

Test 4:

iri: `http://purl.obolibrary.org/obo/UBERON_0001793`
quality: ` http://purl.obolibrary.org/obo/PATO_0000001`
parts: `false`
historical_homologs: `false`
serial_homologs: `false`
limit: `20`
offset: `0`
total: `true`

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001793&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000001&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 12
}
```

New KB:
```
curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001793&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000001&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":16}
```

2021-02-10 17:56 UTC, Shalsh23 commented
Test 5:

Test 4:

iri: `http://purl.obolibrary.org/obo/UBERON_0008897`
quality: `http://purl.obolibrary.org/obo/PATO_0000052`
parts: `false`
historical_homologs: `false`
serial_homologs: `false`
limit: `20`
offset: `0`
total: `true`

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000052&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 283
}
```

New KB:
```
curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000052&parts=false&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":120}
```

2021-02-10 19:47 UTC, Shalsh23 commented
Test 6:

iri: `http://purl.obolibrary.org/obo/UBERON_0008897`
quality: `http://purl.obolibrary.org/obo/PATO_0000052`
parts: `true`
historical_homologs: `false`
serial_homologs: `false`
limit: `20`
offset: `0`
total: `true`

Old KB:
```
curl -X GET "https://kb.phenoscape.org/api/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000052&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{
  "total": 311
}
```

New KB:
```
curl -X GET "http://localhost:8082/gene/affecting_entity_phenotype?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897&quality=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000052&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=true" -H "accept: application/json"
```
```
{"total":131}
```

2021-02-11 16:13 UTC, balhoff commented
The reduced results for E+Q queries are correct. This update fixes a bug that was returning too many results in the old code.

2021-02-11 16:13 UTC, balhoff approved these changes

2021-02-15 20:14 UTC, merged