Add specifier property and and value as parameters to jaccard and mat…
phenoscape/phenoscape-kb-services pull request #485
Opened 2021-09-10 15:42 UTC by Shalsh23

…rix service

2021-09-10 15:43 UTC, Shalsh23 commented
WIP: tests

2021-09-13 21:15 UTC, Shalsh23 commented
Test 1:
iris: `["http://purl.obolibrary.org/obo/UBERON_0000151","http://purl.obolibrary.org/obo/UBERON_0000152","http://purl.obolibrary.org/obo/UBERON_0003097"]`
subject_property: `http://purl.obolibrary.org/obo/caro#part_of`
subject_value: `http://purl.obolibrary.org/obo/CARO_0000000`

```
curl -X GET "http://localhost:8082/similarity/jaccard?iris=%5B%22http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000151%22%2C%22http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000152%22%2C%22http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0003097%22%5D&subject_property=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fcaro%23part_of&subject_value=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCARO_0000000" -H "accept: application/json"
```
```
{"results":[{"terms":["http://purl.obolibrary.org/obo/UBERON_0000151","http://purl.obolibrary.org/obo/UBERON_0000152"],"score":0.6629213483146067},{"terms":["http://purl.obolibrary.org/obo/UBERON_0000151","http://purl.obolibrary.org/obo/UBERON_0003097"],"score":0.5128205128205128},{"terms":["http://purl.obolibrary.org/obo/UBERON_0000152","http://purl.obolibrary.org/obo/UBERON_0003097"],"score":0.4878048780487805}]}%
```

2021-09-14 14:10 UTC, balhoff requested changes

2021-09-14 14:10 UTC, balhoff commented on src/main/resources/swaggerDocs/swagger.yaml
> +          description: SPARQL property path composed of full IRIS. This is used to connect the data resource to count (RDF graph world) to the ontology world. E.g. `<http://purl.obolibrary.org/obo/RO
Why not use a property path that's relevant for our semantic similarity queries? `has_state/describes_phenotype` would be good, with the correct IRIs.

2021-09-14 14:10 UTC, balhoff commented on src/main/resources/swaggerDocs/swagger.yaml
> +          description: SPARQL property path composed of full IRIS. This is used to connect the data resource to count (RDF graph world) to the ontology world. E.g. `<http://purl.obolibrary.org/obo/RO
Same comment as above.

2021-09-14 14:10 UTC, balhoff commented on src/main/scala/org/phenoscape/kb/Main.scala
> +                        validate((subjProp.isEmpty && subjVal.isEmpty) || (subjProp.nonEmpty && subjVal.nonEmpty),
Can you add this validation to the other two services?

2021-09-17 18:51 UTC, balhoff requested changes

2021-09-17 18:51 UTC, balhoff commented on src/main/scala/org/phenoscape/kb/Main.scala
> +                                   "Subject filter property and value must be provided together if at all")
I think this validation needs the same fix.

2021-09-17 18:51 UTC, balhoff commented on src/main/scala/org/phenoscape/kb/Main.scala
> +                                   "Subject filter property and value must be provided together if at all")
This validations needs the fix as well.

2021-09-22 19:51 UTC, balhoff approved these changes

2021-09-22 19:51 UTC, merged